[features]
seeds = false
[programs.devnet]
hello_w = "3dVTBPaADCVUGtDLRMitEdrj86YQLwVHVdsBvJRTn3PD"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/vuhuynh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
